### ISSUE TITLE
Au premier clic sur le bouton, ouvrir la fenêtre options

### ISSUE THREAD

**Issue by wtoscer** [vincnet500/RedmineEasySubmit#5]
Lors de l'installation de l'addon, au premier clic sur le bouton, la fenêtre de soumission de ticket est ouverte, mais il n'y a rien de configuré.
Il serait mieux d'ouvrir la fenêtre d'options à ce moment :-)

**Comment by vincnet500** [comment]
Corrigé en v0.6.
