### ISSUE TITLE
Rajouter un lien vers l'aide de la syntaxe pour la description

### ISSUE THREAD

**Issue by wtoscer** [vincnet500/RedmineEasySubmit#7]
Redmine gère une syntaxe wiki pour la description du ticket.
Il serait bien de rajouter un lien vers http://HOSTNAME/help/fr/wiki_syntax.html au moment de la saisie de la description (voir si on peut choper la locale du navigateur pour la construction du lien)

**Comment by vincnet500** [comment]
Sera ajouté en v0.6 avec un joli lien ! ;)

**Comment by wtoscer** [comment]
il faut gérer la langue du navigateur

**Comment by vincnet500** [comment]
C'est fait ! :)
Bon pour la v0.6.
